items:
  ingot: null
  nugget: null
  powder: null
settings:
  bank_account:
    enable: true
    account_name: RCB
    bill_pool: 0
  coin_value:
    ingot: 1
    nugget: 0.1
    powder: 0.01
display_names:
  ingot: 锭
  nugget: 粒
  powder: 尘
text:
  button: CLICK