name: ZthCoinBank
version: '${project.version}'
main: ink.magma.zthcoinbank.ZthCoinBank
softdepend: [Vault]
commands:
  coin:
    description: 主命令
    usage: /<command> <子命令>
permissions:
  zth.coinbank.admin:
    description: "允许使用管理员功能"
    default: op